
		<section id="title" class="high">
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">
						<table width="100%">
							<tr>
								<td><img src="../images/freetrial.png"></td>
								<td><h1>A trial is worth a thousand words </h1>
								<h4>14 days. 50 candidates. No credit card. </h4></td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</section>
		
		<section id="jobs">
			<div class="container" class="color2">
	
				<form>
					<div class="row">
						<div class="col-sm-4">
							<h2>Register</h2>
							<div class="form-group" id="job-email-group">
								<label for="job-email">Company Name</label>
								<input type="text" class="form-control" id="company-name">
							</div>
							<div class="form-group" id="job-location-group">
								<label for="job-location">Name</label>
								<input type="text" class="form-control" id="name">
							</div>
							<div class="form-group">
								<label for="register-password2">Last Name</label>
								<input type="password" class="form-control" id="last-name">
							</div>
							<div class="form-group">
								<label for="register-password2">Email</label>
								<input type="password" class="form-control" id="email">
							</div>	
							<div class="form-group">
								<label for="register-password2">Password</label>
								<input type="password" class="form-control" id="password">
							</div>			
						</div>
						<div class="col-sm-4">
							<h2>Company Details</h2>
							<div class="form-group" id="company-name-group">
								<label for="company-name">Company Name</label>
								<input type="text" class="form-control" id="company-name" placeholder="Enter company name">
							</div>
							<div class="form-group">
								<label for="register-name">Username</label>
								<input id="username" class="form-control" type="text">
							</div>
							<div class="form-group">
								<label for="register-name">Password</label>
								<input id="register-name" class="form-control" type="text">
							</div>
						</div>
					</div>

					</div>
					<div class="row text-center">
						<p>&nbsp;</p>
						<a href="#" class="btn btn-primary btn-lg">Preview <i class="fa fa-arrow-right"></i></a>
					</div>
				</form>

			</div>
		</section>
