<style>
.box1 {
	height:300px;
	margin-left: auto;
	margin-top: auto;
	text-align: top;
}

.high{
	margin-top: 50px;
}
</style>

<section id="story"  class="high">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<table width="100%">
					<tr>
						<td><img src="../images/freetrial.png"></td>
						<td><h1>A trial is worth a thousand words </h1></td>
					</tr>
				</table>
				</br></br>
				<h4>Assessments in </h4>
				<h5>PHP, JAVA, HTML, SQL, DRUPAL, MVC, PROGRAMMING, etc.</h5>
			</div>
			<div class="col-sm-6">-
				<h2>Registration</h2>
				<form id="registration-form" name="registration-form">
					<div>
						<div class="form-group" id="registration-company-group">
							<label for="job-email">Company Name</label>
							<input type="text" class="form-control" id="registration-company">
						</div>
						<div class="form-group" id="registration-first-group">
							<label for="job-location">First Name</label>
							<input type="text" class="form-control" id="registration-first">
						</div>
						<div class="form-group" id="registration-last-group">
							<label for="register-last">Last Name</label>
							<input type="text" class="form-control" id="registration-last">
						</div>
						<div class="form-group" id="registration-email-group">
							<label for="register-password">Email / User Name</label>
							<input type="text" class="form-control" id="registration-email">
						</div>	
						<div class="form-group" id="registration-password-group">
							<label for="register-password">Password</label>
							<input type="password" class="form-control" id="registration-password">
						</div>
						<button type="submit" class="btn btn-primary">Submit</button>	
					</div>
				</form>
			</div>
		</div>
	</div>
</section>




