<style>
	
	.box1 {
		height:500px;
		 margin-left: auto ;
		  margin-top: auto ;
		  text-align:top;
	}
	
	.space1 {
		height:50px;
	}
	
	.centered{
		text-aligin:middle;
	}
	
	.box2{
		height:500px;
		margin-left: auto ;
		margin-top: auto ;
		text-align:top;
	}

	.high{
		margin-top: 50px;
	}

	section {
	    padding: 20px 0;
	}

</style>		
		
		<!-- ============ TITLE START ============ -->

		<section id="title" class="high">
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">

						<table width="100%">
							<tr>
								<td><img src="../images/savetime.png"></td>
								<td><h1>Unityassessments saves you time and money</h1>
							</tr>
						</table>

					</div>
				</div>
			</div>
		</section>

		<!-- ============ TITLE END ============ -->

		<!-- ============ STORY START ============ -->

		<section id="story" >
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h2>Create programming tests</h2>
						<p>Pick from a constantly evolving <b>pool of 100+ tasks of different types at three difficulty levels.</b> We believe that good, correct and efficient code impresses, no matter what language it's written in, since our tasks are <b>language independent.</b></p>
					</div>
					<div class="col-sm-6">
						<h2>Invite candidates</h2>
						<p>Upload your candidates' data and <b>email them via UnityAssessments or manually.</b></p>
					</div>
				</div>
			</div>
		</section>

		<section id="story">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h2>Candidates code online</h2>
						<p>Your candidates solve their test <b>wherever they are, whenever they like.</b> The coding environment is built </b>by programmers, for programmers.</b> See a demo test.</p>
					</div>
					<div class="col-sm-6">
						<h2>Compare and filter based on facts</h2>
						<p><b>You receive a detailed test report instantly</b> for each candidate, and you can compare them using consistent metrics and a pool of assessments we've done to date. See a <b>candidate report </b></p>
					</div>
				</div>
			</div>
		</section>
		
		<section id="story" class="section2">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h2>Interview only the best ones</h2>
						<p>Save your precious time and reduce the frustration of your tech staff. Spend necessary time for follow-up interviews only on qualified, inspiring candidates.</p>
					</div>
					<div class="col-sm-6 color3">
						<div class="featured-job">
							<img class="img-circle pull-left" alt="" src="../images/peterlord.jpg" width="75px">
						<div class="title text-left" >
							<h5>Peter Lord</h5>
							<p>CEO</p>
						</div>
						<div class="container"></div>
						<div class="description"><b>"We have used UnityAssessments since rapidly expanding our tech team and have found UnityAssessments to save us not only money but a lot of time wasting caused by recruitment companies! The aesthetics and support are of an exceptionally high standard." </b></div>
						</div>
					</div>
				</div>
			</div>
		</section>
		
