<!DOCTYPE html>
<html>
	<head>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta name="description" content="Jobseek - Job Board Responsive HTML Template">
		<meta name="author" content="Coffeecream Themes, armando@unityassessments.com.au">
		<title>Unityassessents - a recruitment plaftorm for the IT sector.</title>
		<link rel="shortcut icon" href="images/favicon.png">

		<!-- Main Stylesheet -->
		<link href="css/style.css" rel="stylesheet">

		<!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="js/html5shiv.js"></script>
		<script src="js/respond.min.js"></script>
		<![endif]-->

	</head>

<style>
header {
    background: #14b1bb none repeat scroll 0 0;
    color: #fff;
    left: 0;
    line-height: 40px;
    padding: 10px 0;
    position: fixed;
    top: 0;
    width: 100%;
    z-index: 10000;
}
</style>

<script>
  	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  	ga('create', 'UA-74966857-1', 'auto');
 	ga('send', 'pageview');
</script>

	<body id="home">

		<!-- ============ NAVBAR START ============ -->
		<div class="fm-container"></div>
		<!-- ============ NAVBAR END ============ -->

		<!-- ============ HEADER START ============ -->
		<header>
			<div id="header-background" style="display:absolute;"></div>			
			<div class="container">
				<div id="logo"  style="float:left;">
					<a href="/#" class="fm-button"><img src="images/logo-assessment.png" /></a>
				</div>
				
				<div style="float:right;margin-top:20px;margin-right:0px;">

					<h4><a href="/howitworks">How it works</a> - 
					<a href="/pricing">Pricing</a> - 
					<?php 
					if(APPLICATION_ENV=="development"){ ?>
						<a href="http://blog.dev-Unityassessments.com.au/" target="_blank">Blog</a>
					<?php }else { ?>
						<a href="http://blog.Unityassessments.com.au/" target="_blank">Blog</a>
					<?php } ?>
					-
					<a href="#" class="link-register" id="menu-signup">Login</a>
				</div>
				
			</div>
		</header>
		<!-- ============ HEADER END ============ -->

		 <?php echo $this->content; ?>

		<!-- ============ CONTACT START ============ -->
		<section id="contact" class="color2">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h2>Drop us a line</h2>
						<form role="form" name="contact-form" id="contact-form" action="/services">
							<div class="form-group" id="contact-name-group">
								<label for="contact-name" class="sr-only">Name</label>
								<input type="text" class="form-control" id="contact-name" placeholder="Name">
							</div>
							<div class="form-group" id="contact-email-group">
								<label for="contact-email" class="sr-only">Email</label>
								<input type="email" class="form-control" id="contact-email" placeholder="Email">
							</div>
							<div class="form-group" id="contact-subject-group">
								<label for="contact-subject" class="sr-only">Subject</label>
								<input type="text" class="form-control" id="contact-subject" placeholder="Subject">
							</div>
							<div class="form-group" id="contact-message-group">
								<label for="contact-message" class="sr-only">Message</label>
								<textarea class="form-control" rows="3" id="contact-message"></textarea>
							</div>
							<button type="submit" class="btn btn-default">Submit</button>
						</form>
					</div>
					<div class="col-sm-6">
						<h2>Visit our office</h2>
						<div class="row">
							<div class="col-sm-6">
								
							</div>
							<div class="col-sm-6">
								<h5></h5>Sydney
								<p>A56 / 252 Botany Rd<br>
								Sydney , NSW<br>
								Australia</p>
								<p><i class="fa fa-phone"></i>+61 406020681<br>
								<i class="fa fa-fax"></i><br>
								<i class="fa fa-envelope"></i><a href="mailto:armando@unityassessments.com.au">	armando@unityassessments.com.au</a></p>
								<p><i class="fa fa-clock-o"></i>Mon-Fri 9am - 5pm<br>
								<i class="fa fa-clock-o"></i>Sat 10am - 2pm<br>
								<i class="fa fa-clock-o"></i>Sun Closed</p>
								</i>
							</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- ============ CONTACT END ============ -->

		<!-- ============ FOOTER START ============ -->
		<footer>
			<div id="prefooter">
			
				<div class="container">
					<div class="row">
						<div class="col-sm-6" id="newsletter">
							<h2>Newsletter</h2>
							<form class="form-inline">
								<div class="form-group">
									<label class="sr-only" for="newsletter-email">Email address</label>
									<input type="email" class="form-control" id="newsletter-email" placeholder="Email address">
								</div>
								<button type="submit" class="btn btn-primary">Sign up</button>
							</form>
						</div>
						<div class="col-sm-6" id="social-networks">
							<h2>Get in touch</h2>
							<a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
							<a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
							<a href="#"><i class="fa fa-2x fa-google-plus-square"></i></a>
							<a href="#"><i class="fa fa-2x fa-youtube-square"></i></a>
							<a href="#"><i class="fa fa-2x fa-vimeo-square"></i></a>
							<a href="#"><i class="fa fa-2x fa-pinterest-square"></i></a>
							<a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a> 
						</div>
					</div>
				</div>
			</div>
			
			<div id="credits">
				<div class="container text-center">
					<div class="row">
						<div class="col-sm-12">
							<br>
							&copy; 2016 Unityassessments - Your place for technical tests.<br>
						</div>
					</div>
				</div>
			</div>
			
		</footer>
		<!-- ============ FOOTER END ============ -->

		<!-- ============ REGISTER START ============ -->
		<div class="popup" id="register">
			<div class="popup-form">
				<div class="popup-header">
					<a class="close"><i class="fa fa-remove fa-lg"></i></a>
					<h2>Login</h2>
				</div>
				<form>
				<div class="credentials">
					<div class="form-group">
						<label for="register-username">Email</label>
						<input type="text" class="form-control">
					</div>
					<div class="form-group">
						<label for="register-password1">Password</label>
						<input type="password" class="form-control">
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
				</form>
			</div>
		</div>

		<!-- ============ REGISTER END ============ -->
		<script src="js/modernizr.custom.79639.js"></script>
		<script src="js/jquery-1.11.2.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/retina.min.js"></script>
		<script src="js/scrollReveal.min.js"></script>
		<script src="js/jquery.flexmenu.js"></script>
		<script src="js/jquery.ba-cond.min.js"></script>
		<script src="js/jquery.slitslider.js"></script>
		<script src="js/owl.carousel.min.js"></script>
		<script src="js/parallax.js"></script>
		<script src="js/jquery.counterup.min.js"></script>
		<script src="js/waypoints.min.js"></script>
		<script src="js/jquery.nouislider.all.min.js"></script>
		<script src="js/bootstrap3-wysihtml5.all.min.js"></script>
		<script src="js/jflickrfeed.min.js"></script>
		<script src="js/fancybox.pack.js"></script>
		<script src="js/magic.js"></script>
		<script src="js/settings.js"></script>
		<script>/*<![CDATA[*/window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(c){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var o=this.createElement("script");n&&(this.domain=n),o.id="js-iframe-async",o.src=e,this.t=+new Date,this.zendeskHost=t,this.zEQueue=a,this.body.appendChild(o)},o.write('<body onload="document._l();">'),o.close()}("https://assets.zendesk.com/embeddable_framework/main.js","Unityassessments.zendesk.com");
		/*]]>*/</script>
		<!-- End of Unityassessments Zendesk Widget script -->
	
	</body>


</html>