<style>

	.box1 {
		height:300px;
		 margin-left: auto;
		  margin-top: auto;
		  text-align: top;
	}

	.high{
		margin-top: 50px;
	}

</style>

		<section id="story"  class="high">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">

						<table width="100%">
							<tr>
								<td><img src="../images/freetrial.png"></td>
								<td><h1>A trial is worth a thousand words </h1>
							</tr>
						</table>
						<br><br>
						<h4>Assessments in </h4>
						<h5>PHP, JAVA, HTML, SQL, DRUPAL, MVC, PROGRAMMING, etc.</h5>

					</div>
					<div class="col-sm-6">
						<h2>Registration</h2>
						<form action="/registration">
							<div>
								<div class="form-group" id="job-email-group">
									<label for="job-email">Company Name</label>
									<input type="text" class="form-control" id="company-name">
								</div>
								<div class="form-group" id="job-location-group">
									<label for="job-location">Name</label>
									<input type="text" class="form-control" id="name">
								</div>
								<div class="form-group">
									<label for="last-name">Last Name</label>
									<input type="text" class="form-control" id="last-name">
								</div>
								<div class="form-group">
									<label for="user-name">Email / User name</label>
									<input type="text" class="form-control" id="email">
								</div>
								<div class="form-group">
									<label for="register-password">Password</label>
									<input type="password" class="form-control" id="password">
								</div>
								<div class="form-group">
									<button type="submit" class="btn btn-primary">Submit</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</section>





