<style>

.box1 {
	height:500px;
	 margin-left: auto ;
	  margin-top: auto ;
	  text-align:top;
}

.space1 {
	height:50px;
}

.centered{
	text-aligin:middle;
}

.box2 {
	height:500px;
	margin-left: auto ;
	margin-top: auto ;
	text-align:top;
}

</style>

		<!-- ============ SLIDES START ============ -->

		<div id="slider" class="sl-slider-wrapper">

			<div class="sl-slider">

				<div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="-25" data-slice2-rotation="-25" data-slice1-scale="2" data-slice2-scale="2">
					<div class="sl-slide-inner">
						<div class="bg-img bg-img-1"></div>
						<div class="tint"></div>
						<div class="slide-content">
							<h2>Hiring programmers made easy</h2>
							<h3>Programmer testing solution that matches your job descriptions</h3>
							<p><a href="jobs.html" class="btn btn-lg btn-default">Try our recruiting platforms</a></p>
						</div>
					</div>
				</div>

				<div class="sl-slide" data-orientation="vertical" data-slice1-rotation="10" data-slice2-rotation="-15" data-slice1-scale="1.5" data-slice2-scale="1.5">
					<div class="sl-slide-inner">
						<div class="bg-img bg-img-2"></div>
						<div class="tint"></div>
						<div class="slide-content">
							<h2>I'm a programmer!</h2>
							<h3>Take our free lessons & challenges</h3>
							<p><a href="candidates.html" class="btn btn-lg btn-default">Upgrade your skills now</a></p>
						</div>
					</div>
				</div>
				
			</div>

			<nav id="nav-arrows" class="nav-arrows">
				<span class="nav-arrow-prev">Previous</span>
				<span class="nav-arrow-next">Next</span>
			</nav>

			<nav id="nav-dots" class="nav-dots">
				<span class="nav-dot-current"></span>
				<span></span>
			</nav>

		</div>

		<!-- ============ SLIDES END ============ -->
	

		<!-- ============ Your company's testing solution START ============ -->

		<section id="title">
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">
						<h1>Your company's testing solution</h1>
					</div>
				</div>
			</div>
		</section>

		<section id="team" class="color1">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<div class="owl-carousel">

							<!-- Team Member 1 -->
							<div class="team-member text-center img-rounded box1">
								<img src="../images/icons.png" class="img-responsive" alt="" />
								<h5 class="space1">Hire faster</h5>
								<p style="height:100">Filter out candidates who don't meet your standards without involving your technical colleagues.</p>								
							</div>

							<!-- Team Member 2 -->
							<div class="team-member text-center img-rounded box1">
								<img src="../images/icons1.jpg" class="img-responsive" alt="" />
								<h5 class="space1">Hiring made simple</h5>
								<p>Unifyassessments makes testing programmers a breeze, even for recruiters without a technical background.</p>
							</div>

							<!-- Team Member 3 -->
							<div class="team-member text-center img-rounded box1">
								<img src="../images/icons2.jpg" class="img-responsive " alt="" />
								<h5 class="space1">Hire smarter</h5>
								<p>Unifyassessments gives you objective insights into your candidates programming skills, showing you their thinking process before you interview them.</p>
							</div>

							<!-- Team Member 4 -->
							<div class="team-member text-center img-rounded box1">
								<img src="../images/icons4.jpg" class="img-responsive" alt="" />
								<h5 class="space1">Start right now</h5>
								<p>Unifyassessments works right out of the box. No long setups. Programming tasks are ready to be used.</p>
							</div>

						</div>
					</div>
				</div>
			</div>
		</section>

		<!-- ============ Your company's testing solution END ============ -->		
		
		<!-- ============ STATS START ============ -->

		<section id="stats" class="parallax text-center">
			<div class="tint"></div>
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<h1>Depth view of how it works <img src="../images/i_gears.svg" class="img-responsive" alt="" width="100px" /></h1>
					</div>
				</div>
				<div class="row" id="counter">
							
				</div>
				<div class="row">
					<div class="col-sm-12">
						<p><a class="link-register btn btn-primary" href="/howitworks">Read</a></p>
					</div>
				</div>
			</div>
		</section>

		<!-- ============ STATS END ============ -->
		
		<!-- ============ Your company's testing solution START ============ -->
		<section id="title">
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">
						<h1>How online testing works</h1>
					</div>
				</div>
			</div>
		</section>
		<!-- ============ Your company's testing solution END ============ -->
		
		
		<!-- ============ Your company's testing solution START ============ -->

		<section id="team" class="color4">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<div class="owl-carousel centered">
						
							<div class="step" style="float:left;">
								<span class="hanging-number"><h4>1.</h4></span>
								<img alt="Invite" onerror="this.src='../images/icons7.png'; this.onerror=null" src="../images/icons7.png" width="150">
								<h5>Invite your candidates to our automated test</h5>
							</div>
	
							<div class="step">
								<span class="hanging-number"><h4>2.</h4></span>
								<img alt="Invite" onerror="this.src='../images/icons8.png'; this.onerror=null" src="../images/icons8.png" width="150">
								<h5>Get your candidates graded online based on their actual skills</h5>
							</div>
	
							<div class="step">
								<span class="hanging-number"><h4>3.</h4></span>
								<img alt="Invite" onerror="this.src='../images/icons9.png'; this.onerror=null" src="../images/icons9.png" width="150">
								<h5>Enjoy interviewing only the best</h5>
							</div>
							
						</div>
					</div>
				</div>
			</div>
		</section>
		
		<!-- ============ TITLE START ============ -->

		<section id="title" class="color1">
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">
						<h1>UnityAssessments for programmers</h1>
						<h4>See how you can improve your skills.</h4>
					</div>
				</div>
			</div>
		</section>

		<!-- ============ TITLE END ============ -->

		<!-- ============ STORY START ============ -->

		<section id="story" class="color1">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h2>Help me with my test</h2>
						<p>If you have received an invitation to a UnityAssessments test, go ahead and open it now. You don't have to start the test at once, but the information you find there will help you prepare. </p>

						<p>Our FAQ explains what kind of code you will have to write, how your solutions will be evaluated and talks in detail about the testing procedure.</p>
						<button aria-expanded="false" data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button">Do a remo test <span class="caret"></span></button>
					</div>
					<div class="col-sm-6">
						<h2>I want to train</h2>
						<p>UnityAssessments has free training, lessons and challenges for the programming community.</p>

						<p>There are 16 lessons with around 70 training tasks. When you complete a task you will get feedback on its correctness and performance.</p>

						<p>	We also run programming challenges to allow programmers to show off their skills.</p>
						<button aria-expanded="false" data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button">Lessons <span class="caret"></span></button>
					</div>
					
				</div>
			</div>
		</section>

		<!-- ============ STORY END ============ -->
		
		
		