<style>

	.box1 {
		height:300px;
		 margin-left: auto ;
		  margin-top: auto;
		  text-align: top;
	}

	.high{
		margin-top: 50px;
		margin-bottom: 100px;
	}

</style>
				
		<!-- ============ PRICING START ============ -->

		<section id="pricing" class="text-center high">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<h1>Plans &amp; Pricing</h1>
						<h4>Choose a package that fits your needs</h4>
					</div>
				</div>
				<div class="row pricing">
					<div class="col-sm-3">
						<ul>
							<li class="title">FREE Month</li>
							<li class="price">$0</li>
							<li>1 User account</li>
							<li>Up to 10 candidates</li>
							<li>Create your own assessment feature is not included.</li>
							<li><a href="/register?option=1" class="btn btn-primary">Choose</a></li>
						</ul>
					</div>
					<div class="col-sm-3">
						<ul class="popular">
							<li class="title">Startup</li>
							<li class="price">$10</li>
							<li>5 Users account</li>
							<li>Up to 20 candidates</li>
							<li>Create your own assessment feature is included</li>
							<li><a href="/register?option=2" class="btn btn-primary">Choose</a></li>
						</ul>
					</div>
					<div class="col-sm-3">
						<ul>
							<li class="title">Company</li>
							<li class="price">$30</li>
							<li>10 Users account</li>
							<li>Up to 40 candidates</li>
							<li>Create your own assessment feature is included</li>
							<li><a href="/register?option=3" class="btn btn-primary">Choose</a></li>
						</ul>
					</div>
					<div class="col-sm-3">
						<ul>
							<li class="title">Enterprise</li>
							<li class="price">$60</li>
							<li>Unlimited users account</li>
							<li>Unlimited candidates</li>
							<li>Create your own assessment feature is included</li>
							<li><a href="/register?option=4" class="btn btn-primary">Choose</a></li>
						</ul>
					</div>
				</div>
			</div>
		</section>

		<!-- ============ PRICING END ============ -->


		<section id="title"  class="color1" >
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">
						<h1>Unityassessments for programmers</h1>
						<h4>See how you can improve your skills.</h4>
					</div>
				</div>
			</div>
		</section>

		<section id="team" class="color1">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<div class="owl-carousel centered">

							<!-- Team Member 1 -->
							<div class="team-member text-center img-rounded box1 section2">
								<img src="../images/feature_report.svg" class="img-responsive" alt="" />
								<h5 class="space1">SCREEN OBJECTIVELY</h5>
								<p style="height:100">using top quality tasks.</p>								
							</div>

							<!-- Team Member 2 -->
							<div class="team-member text-center img-rounded box1  section2">
								<img src="../images/feature_challenge.svg" class="img-responsive" alt="" />
								<h5 class="space1">SOURCE MORE CANDIDATES </h5>
								<p>with customized challenges .</p>
							</div>

							<!-- Team Member 3 -->
							<div class="team-member text-center img-rounded box1  section2">
								<img src="../images/feature_task.svg" class="img-responsive " alt="" />
								<h5 class="space1">GAIN DEEPER INSIGHT </h5>
								<p>with comprehensive reports.</p>
							</div>

							<!-- Team Member 3 -->
							<div class="team-member text-center img-rounded box1  section2">
								<img src="../images/cash.png" class="img-responsive " alt="" width="120px">
								<h5 class="space1">SAVE MONEY </h5>
								<p>Add a real value to yurs services.</p>
							</div>

						</div>
					</div>
				</div>
			</div>
		</section>

		<!-- ============ Your company's testing solution START ============ -->
		<section id="title" class="high">
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">

						<table width="900">
							<tr>
								<td><img src="../images/cash.png" width="120px"></td>
								<td>
								<h1>Questions about pricing? </h1>
								<h4>Call or use the chat box to talk with us </h4>
								</td>
							</tr>
						</table>

					</div>
				</div>
			</div>
		</section>
		<!-- ============ Your company's testing solution END ============ -->	

		<!-- ============ STORY START ============ -->
		<section id="story" >
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h2>How much does a custom assessment? </h2>
						<p>Our price depends on your tech hiring needs. Drop us a line and we will get you a customized quote right away.</p>
					</div>
					<div class="col-sm-6">
						<h2>Are there any extra training and setup costs? </h2>
						<p>No. We want you to get the most out of Unityassessments straight away, so onboarding, training and support come for free.</p>
					</div>
				</div>
			</div>
		</section>
		<!-- ============ STORY END ============ -->
		
		<!-- ============ STORY START ============ -->
		<section id="story" >
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h2>Can I get help creating my tests?  </h2>
						<p>Yes. Ask our experts to build a test for your job description and start screening right away. </p>
					</div>
					<div class="col-sm-6">
						<h2>Do you create custom packages? </h2>
						<p>Yes. UnityAssessments is adaptable to your needs and we are happy to customize it accordingly. </p>
					</div>
				</div>
			</div>
		</section>
		<!-- ============ STORY END ============ -->