<style>

	.box1 {
		height:300px;
		 margin-left: auto ;
		  margin-top: auto;
		  text-align: top;
	}

	.high{
		margin-top: 50px;
		margin-bottom: 100px;
	}

</style>

				

		<section id="title" class="high">
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">

						<table width="900">
							<tr>
								<td><img src="../images/cash.png" width="120px"></td>
								<td>
								<h1>Questions about pricing? </h1>
								<h4>Call or use the chat box to talk with us </h4>
								</td>
							</tr>
						</table>

					</div>
				</div>
			</div>
		</section>

		<!-- ============ Your company's testing solution END ============ -->	

		<!-- ============ STORY START ============ -->

		<section id="story" >
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h2>How much does UnityAssessments cost? </h2>
						<p>Our price depends on your tech hiring needs. Drop us a line and we will get you a customized quote right away.</p>
									</div>
					<div class="col-sm-6">
						<h2>Are there any extra training and setup costs? </h2>
						<p>No. We want you to get the most out of UnityAssessments straight away, so onboarding, training and support come for free.</p>
					</div>
					
				</div>
			</div>
		</section>

		<!-- ============ STORY END ============ -->
		
				<!-- ============ STORY START ============ -->

		<section id="story" >
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h2>Can I get help creating my tests?  </h2>
						<p>Yes. Ask our experts to build a test for your job description and start screening right away. </p>
					</div>
					<div class="col-sm-6">
						<h2>Do you create custom packages? </h2>
						<p>Yes. UnityAssessments is adaptable to your needs and we are happy to customize it accordingly. </p>
					</div>
				</div>
			</div>
		</section>

		<!-- ============ STORY END ============ -->


		<section id="title"  class="color1" >
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">
						<h1>Unityssessments for programmers</h1>
						<h4>See how you can improve your skills.</h4>
					</div>
				</div>
			</div>
		</section>

		<section id="team" class="color1">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<div class="owl-carousel centered">

							<!-- Team Member 1 -->
							<div class="team-member text-center img-rounded box1 section2">
								<img src="../images/feature_report.svg" class="img-responsive" alt="" />
								<h5 class="space1">SCREEN OBJECTIVELY</h5>
								<p style="height:100">using top quality tasks.</p>								
							</div>

							<!-- Team Member 2 -->
							<div class="team-member text-center img-rounded box1  section2">
								<img src="../images/feature_challenge.svg" class="img-responsive" alt="" />
								<h5 class="space1">SOURCE MORE CANDIDATES </h5>
								<p>with customized challenges .</p>
							</div>

							<!-- Team Member 3 -->
							<div class="team-member text-center img-rounded box1  section2">
								<img src="../images/feature_task.svg" class="img-responsive " alt="" />
								<h5 class="space1">GAIN DEEPER INSIGHT </h5>
								<p>with comprehensive reports.</p>
							</div>

							<!-- Team Member 3 -->
							<div class="team-member text-center img-rounded box1  section2">
								<img src="../images/cash.png" class="img-responsive " alt="" width="120px">
								<h5 class="space1">SAvE MONBY </h5>
								<p>Add a real value to yurs services.</p>
							</div>

						</div>
					</div>
				</div>
			</div>
		</section>

		<!-- ============ Your company's testing solution START ============ -->
		
